/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
	scheme "github.com/kubernetes-sigs/service-catalog/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterServiceDescriptionsGetter has a method to return a ClusterServiceDescriptionInterface.
// A group's client should implement this interface.
type ClusterServiceDescriptionsGetter interface {
	ClusterServiceDescriptions() ClusterServiceDescriptionInterface
}

// ClusterServiceDescriptionInterface has methods to work with ClusterServiceDescription resources.
type ClusterServiceDescriptionInterface interface {
	Create(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.CreateOptions) (*v1beta1.ClusterServiceDescription, error)
	Update(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.UpdateOptions) (*v1beta1.ClusterServiceDescription, error)
	UpdateStatus(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.UpdateOptions) (*v1beta1.ClusterServiceDescription, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ClusterServiceDescription, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ClusterServiceDescriptionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterServiceDescription, err error)
	ClusterServiceDescriptionExpansion
}

// clusterServiceDescriptions implements ClusterServiceDescriptionInterface
type clusterServiceDescriptions struct {
	client rest.Interface
}

// newClusterServiceDescriptions returns a ClusterServiceDescriptions
func newClusterServiceDescriptions(c *ServicecatalogV1beta1Client) *clusterServiceDescriptions {
	return &clusterServiceDescriptions{
		client: c.RESTClient(),
	}
}

// Get takes name of the clusterServiceDescription, and returns the corresponding clusterServiceDescription object, and an error if there is any.
func (c *clusterServiceDescriptions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ClusterServiceDescription, err error) {
	result = &v1beta1.ClusterServiceDescription{}
	err = c.client.Get().
		Resource("clusterservicedescriptions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterServiceDescriptions that match those selectors.
func (c *clusterServiceDescriptions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ClusterServiceDescriptionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ClusterServiceDescriptionList{}
	err = c.client.Get().
		Resource("clusterservicedescriptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterServiceDescriptions.
func (c *clusterServiceDescriptions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("clusterservicedescriptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterServiceDescription and creates it.  Returns the server's representation of the clusterServiceDescription, and an error, if there is any.
func (c *clusterServiceDescriptions) Create(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.CreateOptions) (result *v1beta1.ClusterServiceDescription, err error) {
	result = &v1beta1.ClusterServiceDescription{}
	err = c.client.Post().
		Resource("clusterservicedescriptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterServiceDescription).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterServiceDescription and updates it. Returns the server's representation of the clusterServiceDescription, and an error, if there is any.
func (c *clusterServiceDescriptions) Update(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.UpdateOptions) (result *v1beta1.ClusterServiceDescription, err error) {
	result = &v1beta1.ClusterServiceDescription{}
	err = c.client.Put().
		Resource("clusterservicedescriptions").
		Name(clusterServiceDescription.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterServiceDescription).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterServiceDescriptions) UpdateStatus(ctx context.Context, clusterServiceDescription *v1beta1.ClusterServiceDescription, opts v1.UpdateOptions) (result *v1beta1.ClusterServiceDescription, err error) {
	result = &v1beta1.ClusterServiceDescription{}
	err = c.client.Put().
		Resource("clusterservicedescriptions").
		Name(clusterServiceDescription.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterServiceDescription).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterServiceDescription and deletes it. Returns an error if one occurs.
func (c *clusterServiceDescriptions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("clusterservicedescriptions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterServiceDescriptions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("clusterservicedescriptions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterServiceDescription.
func (c *clusterServiceDescriptions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterServiceDescription, err error) {
	result = &v1beta1.ClusterServiceDescription{}
	err = c.client.Patch(pt).
		Resource("clusterservicedescriptions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
