/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
	scheme "github.com/kubernetes-sigs/service-catalog/pkg/client/clientset_generated/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ServiceActionsGetter has a method to return a ServiceActionInterface.
// A group's client should implement this interface.
type ServiceActionsGetter interface {
	ServiceActions(namespace string) ServiceActionInterface
}

// ServiceActionInterface has methods to work with ServiceAction resources.
type ServiceActionInterface interface {
	Create(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.CreateOptions) (*v1beta1.ServiceAction, error)
	Update(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.UpdateOptions) (*v1beta1.ServiceAction, error)
	UpdateStatus(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.UpdateOptions) (*v1beta1.ServiceAction, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ServiceAction, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ServiceActionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ServiceAction, err error)
	ServiceActionExpansion
}

// serviceActions implements ServiceActionInterface
type serviceActions struct {
	client rest.Interface
	ns     string
}

// newServiceActions returns a ServiceActions
func newServiceActions(c *ServicecatalogV1beta1Client, namespace string) *serviceActions {
	return &serviceActions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the serviceAction, and returns the corresponding serviceAction object, and an error if there is any.
func (c *serviceActions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ServiceAction, err error) {
	result = &v1beta1.ServiceAction{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceactions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ServiceActions that match those selectors.
func (c *serviceActions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ServiceActionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ServiceActionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("serviceactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested serviceActions.
func (c *serviceActions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("serviceactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a serviceAction and creates it.  Returns the server's representation of the serviceAction, and an error, if there is any.
func (c *serviceActions) Create(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.CreateOptions) (result *v1beta1.ServiceAction, err error) {
	result = &v1beta1.ServiceAction{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("serviceactions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAction).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a serviceAction and updates it. Returns the server's representation of the serviceAction, and an error, if there is any.
func (c *serviceActions) Update(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.UpdateOptions) (result *v1beta1.ServiceAction, err error) {
	result = &v1beta1.ServiceAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceactions").
		Name(serviceAction.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAction).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *serviceActions) UpdateStatus(ctx context.Context, serviceAction *v1beta1.ServiceAction, opts v1.UpdateOptions) (result *v1beta1.ServiceAction, err error) {
	result = &v1beta1.ServiceAction{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("serviceactions").
		Name(serviceAction.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(serviceAction).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the serviceAction and deletes it. Returns an error if one occurs.
func (c *serviceActions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceactions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *serviceActions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("serviceactions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched serviceAction.
func (c *serviceActions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ServiceAction, err error) {
	result = &v1beta1.ServiceAction{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("serviceactions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
