/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/kubernetes-sigs/service-catalog/pkg/apis/servicecatalog/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterServiceExtensions implements ClusterServiceExtensionInterface
type FakeClusterServiceExtensions struct {
	Fake *FakeServicecatalogV1beta1
}

var clusterserviceextensionsResource = schema.GroupVersionResource{Group: "servicecatalog.k8s.io", Version: "v1beta1", Resource: "clusterserviceextensions"}

var clusterserviceextensionsKind = schema.GroupVersionKind{Group: "servicecatalog.k8s.io", Version: "v1beta1", Kind: "ClusterServiceExtension"}

// Get takes name of the clusterServiceExtension, and returns the corresponding clusterServiceExtension object, and an error if there is any.
func (c *FakeClusterServiceExtensions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ClusterServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(clusterserviceextensionsResource, name), &v1beta1.ClusterServiceExtension{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterServiceExtension), err
}

// List takes label and field selectors, and returns the list of ClusterServiceExtensions that match those selectors.
func (c *FakeClusterServiceExtensions) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ClusterServiceExtensionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(clusterserviceextensionsResource, clusterserviceextensionsKind, opts), &v1beta1.ClusterServiceExtensionList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ClusterServiceExtensionList{ListMeta: obj.(*v1beta1.ClusterServiceExtensionList).ListMeta}
	for _, item := range obj.(*v1beta1.ClusterServiceExtensionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterServiceExtensions.
func (c *FakeClusterServiceExtensions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(clusterserviceextensionsResource, opts))
}

// Create takes the representation of a clusterServiceExtension and creates it.  Returns the server's representation of the clusterServiceExtension, and an error, if there is any.
func (c *FakeClusterServiceExtensions) Create(ctx context.Context, clusterServiceExtension *v1beta1.ClusterServiceExtension, opts v1.CreateOptions) (result *v1beta1.ClusterServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(clusterserviceextensionsResource, clusterServiceExtension), &v1beta1.ClusterServiceExtension{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterServiceExtension), err
}

// Update takes the representation of a clusterServiceExtension and updates it. Returns the server's representation of the clusterServiceExtension, and an error, if there is any.
func (c *FakeClusterServiceExtensions) Update(ctx context.Context, clusterServiceExtension *v1beta1.ClusterServiceExtension, opts v1.UpdateOptions) (result *v1beta1.ClusterServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(clusterserviceextensionsResource, clusterServiceExtension), &v1beta1.ClusterServiceExtension{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterServiceExtension), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterServiceExtensions) UpdateStatus(ctx context.Context, clusterServiceExtension *v1beta1.ClusterServiceExtension, opts v1.UpdateOptions) (*v1beta1.ClusterServiceExtension, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(clusterserviceextensionsResource, "status", clusterServiceExtension), &v1beta1.ClusterServiceExtension{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterServiceExtension), err
}

// Delete takes name of the clusterServiceExtension and deletes it. Returns an error if one occurs.
func (c *FakeClusterServiceExtensions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(clusterserviceextensionsResource, name), &v1beta1.ClusterServiceExtension{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterServiceExtensions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(clusterserviceextensionsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ClusterServiceExtensionList{})
	return err
}

// Patch applies the patch and returns the patched clusterServiceExtension.
func (c *FakeClusterServiceExtensions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ClusterServiceExtension, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(clusterserviceextensionsResource, name, pt, data, subresources...), &v1beta1.ClusterServiceExtension{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ClusterServiceExtension), err
}
